export const TOUR_LIMITS = {
    TITLE_MAX_LENGTH: 100,
    PRICE_MAX_VALUE: 100000,
    CAPACITY_MAX_VALUE: 50,
    DESCRIPTION_MAX_LENGTH: 750,
    INCLUDED_MAX_ITEMS: 5,
    EXCLUDED_MAX_ITEMS: 5,
    IMAGES_MAX_ITEMS: 5
};
